var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-1.html'
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-2.html',
      minify: {}
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-3.html',
      minify: {
        removeComments: true,// 默认值false；是否移除`html`注释
        collapseWhitespace: true,// 是否移除空格	折叠有助于文档树中文本节点的空白	默认值: false
      }
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-4.html',
      minify: {
        removeComments: true, // 默认值false；是否移除`html`注释
        collapseWhitespace: true, // 是否移除空格	折叠有助于文档树中文本节点的空白	默认值: false
        preserveLineBreaks: true //	标签之间的空格包含换行符时，请务必合拢到1个换行符（永远不要将其完全删除）。必须与collapseWhitespace=true	默认值: false
      }
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-5.html',
      minify: {
        removeComments: true,// 默认值false；是否移除`html`注释
        processConditionalComments:true,//	通过Minifier处理条件注释的内容	默认值: false
        removeEmptyAttributes: true,// 删除所有带有仅空格值的属性
        removeEmptyElements: true,// 删除所有内容为空的元素
        removeOptionalTags: true,// 删除可选标签
        minifyJS: true,// 默认值false；是否压缩html里的js（使用`uglify-js`进行的压缩）
        minifyCSS: true,// 默认值false；是否压缩html里的css（使用`clean-css`进行的压缩）
        // removeAttributeQuotes: true // 移除属性的引号
      }
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
      filename: 'index-99.html',
      minify: {
        caseSensitive:true,//	以区分大小写的方式处理属性（适用于自定义HTML标签）	默认值: false
        collapseBooleanAttributes:true,//	从布尔属性中省略属性值	默认值: false
        collapseInlineTagWhitespace:true,// 压缩行级元素的空白，会保留&nbsp;实体空格	display:inline;折叠时，请勿在元素之间留任何空间。必须与collapseWhitespace=true	默认值: false
        collapseWhitespace:true,// 是否移除空格	折叠有助于文档树中文本节点的空白	默认值: false
        conservativeCollapse:false,//	始终折叠到1个空间（永远不要将其完全删除）。必须与collapseWhitespace=true	默认值: false
        continueOnParseError:true,//	处理解析错误而不是中止。	默认值: false
        // customAttrAssign:true,//	允许支持自定义属性分配表达式的正则表达式数组（例如'<div flex?="{{mode != cover}}"></div>'）	[ ]
        // customAttrCollapse:true,//	指定自定义属性以从中删除换行符的正则表达式（例如/ng-class/）	
        // customAttrSurround:true,//	允许支持自定义属性环绕表达式的正则表达式数组（例如<input {{#if value}}checked="checked"{{/if}}>）	[ ]
        // customEventAttributes:true,//	正则表达式数组，可支持的自定义事件属性minifyJS（例如ng-click）	[ /^on[a-z]{3,}$/ ]
        decodeEntities:true,//	尽可能使用直接Unicode字符	默认值: false
        html5:true,//	根据HTML5规范解析输入	默认值: true
        ignoreCustomComments:true,//	匹配时允许忽略某些注释的正则表达式数组	[ /^!/ ]
        // ignoreCustomFragments:true,//	regex'es允许忽略某些片段的阵列，当一致时（例如<?php ... ?>，{{ ... }}等）	[ /<%[\s\S]*?%>/, /<\?[\s\S]*?\?>/ ]
        includeAutoGeneratedTags:true,//	插入HTML解析器生成的标签	默认值: true
        keepClosingSlash:true,//	在单例元素上保留斜线	默认值: false
        // maxLineLength:true,//	指定最大行长。压缩的输出将在有效的HTML分割点处由换行符分割	
        minifyCSS:true,// 是否压缩html里的css（使用`clean-css`进行的压缩）	缩小样式元素和样式属性中的CSS（使用clean-css）	默认值: false（可能是true，Object，Function(text, type)）
        minifyJS:true,// 是否压缩html里的js（使用`uglify-js`进行的压缩）	缩小脚本元素和事件属性中的JavaScript（使用UglifyJS）	默认值: false（可能是true，Object，Function(text, inline)）
        minifyURLs:true,//	缩小各种属性中的URL（使用relatedurl）	默认值: false（可能是String，Object，Function(text)）
        preserveLineBreaks:false,//	标签之间的空格包含换行符时，请务必合拢到1个换行符（永远不要将其完全删除）。必须与collapseWhitespace=true	默认值: false
        preventAttributesEscaping:true,//	防止转义属性值	默认值: false
        processConditionalComments:true,//	通过Minifier处理条件注释的内容	默认值: false
        // processScripts:true,//	对应于类型脚本的元素串的阵列通过minifier（例如处理text/ng-template，text/x-handlebars-template等）	[ ]
        // quoteCharacter:true,//	用于属性值的引号类型（“或”）	
        removeAttributeQuotes:false,// 移除属性的引号	默认值: false
        removeComments:true,// 是否移除`html`注释	删除HTML注释	默认值: false
        removeEmptyAttributes:true,//	删除所有带有仅空格值的属性	默认值: false（可能是true，Function(attrName, tag)）
        removeEmptyElements:true,//	删除所有内容为空的元素	默认值: false
        removeOptionalTags: false,//	删除可选标签	默认值: false
        removeRedundantAttributes:true,//	当值匹配默认值时删除属性。	默认值: false
        removeScriptTypeAttributes:true,//	type="text/javascript"从script标签中删除。其他type属性值保持不变	默认值: false
        removeStyleLinkTypeAttributes:true,//	type="text/css"从style和link标签中删除。其他type属性值保持不变	默认值: false
        removeTagWhitespace:false,//	尽可能删除属性之间的空间（注意，这将导致无效的HTML！）	默认值: false
        sortAttributes:true,//	按频率对属性进行排序	默认值: false
        sortClassName:true,//	按频率对样式类进行排序	默认值: false
        trimCustomFragments:true,//	修剪周围的空白区域ignoreCustomFragments。	默认值: false
        useShortDoctype:true//	doctype用短（HTML5）文档类型替换	默认值: false
      }
    }),
  ]
}