
// size: (...)
// constructor: ƒ Set()
// has: ƒ has()
// add: ƒ add()
// delete: ƒ delete()
// clear: ƒ clear()
// entries: ƒ entries()
// forEach: ƒ forEach()
// values: ƒ values()
// keys: ƒ values()
// toJSON: ƒ toJSON()
// Symbol(Symbol.toStringTag): "Set"
// Symbol(Symbol.iterator): ƒ values()
// get size: ƒ size()